// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5CZ31eF7EQrmlnU41lZtjfy16RM4iQyc',
    appId: '1:1068241975522:web:e20186bb9fff04f82b06bb',
    messagingSenderId: '1068241975522',
    projectId: 'chatapp-f0254',
    authDomain: 'chatapp-f0254.firebaseapp.com',
    storageBucket: 'chatapp-f0254.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChPsZ8w1JSR-z-mKiS16Hz1fJBv8w6TbA',
    appId: '1:1068241975522:android:3065d234df2c06052b06bb',
    messagingSenderId: '1068241975522',
    projectId: 'chatapp-f0254',
    storageBucket: 'chatapp-f0254.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt27jmpMFfZ75AZgs9SVr_N3PDTPA3k94',
    appId: '1:1068241975522:ios:934e0ebdb42dfe8e2b06bb',
    messagingSenderId: '1068241975522',
    projectId: 'chatapp-f0254',
    storageBucket: 'chatapp-f0254.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt27jmpMFfZ75AZgs9SVr_N3PDTPA3k94',
    appId: '1:1068241975522:ios:934e0ebdb42dfe8e2b06bb',
    messagingSenderId: '1068241975522',
    projectId: 'chatapp-f0254',
    storageBucket: 'chatapp-f0254.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5CZ31eF7EQrmlnU41lZtjfy16RM4iQyc',
    appId: '1:1068241975522:web:8ab23d8d618f26f62b06bb',
    messagingSenderId: '1068241975522',
    projectId: 'chatapp-f0254',
    authDomain: 'chatapp-f0254.firebaseapp.com',
    storageBucket: 'chatapp-f0254.firebasestorage.app',
  );
}
